[package]
name = "asset_loader_system"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]
world = { path = "../../world" }
gfx = { path = "../../gfx" }
logger = { path = "../../logger" }
