[package]
name = "nshell"
version = "0.1.0"
edition = "2021"

[dependencies]
core_executor = { path = "../../core_executor" }
input = { path = "../../input" }
models = { path = "../../models" }
network = { path = "../../network" }
platform = { path = "../../platform" }
plugin_loader = { path = "../../plugin_loader" }
render = { path = "../../render" }
world = { path = "../../world" }

smol = "1.2.5"
futures-util = "0.3.23"

# workspace
async-lock = { workspace = true }
futures-lite = { workspace = true }
structopt = { workspace = true }
