[package]
name = "nshell"
version = "0.1.0"
edition = "2021"

[dependencies]
core_executor = { path = "../../core_executor" }
input = { path = "../../input" }
platform = { path = "../../platform" }
render = { path = "../../render" }
world = { path = "../../world" }
logger = { path = "../../logger" }

# systems
ash_renderer_system = { path = "../../systems/ash_renderer_system" }
asset_loader_system = { path = "../../systems/asset_loader_system" }
net_sync_system = { path = "../../systems/net_sync_system" }
world_update_system = { path = "../../systems/world_update_system" }

smol = "1.2.5"
futures-util = "0.3.28"
serde = { version = "1.0.130", features = ["derive"] }
structopt-yaml = "0.4.6"

# workspace
histogram = { workspace = true }
async-lock = { workspace = true }
futures-lite = { workspace = true }
structopt = { workspace = true }
