[package]
name = "nshell"
version = "0.1.0"
edition = "2021"

[dependencies]
plugin_loader = { path = "../../plugin_loader" }
render = { path = "../../render" }
input = { path = "../../input" }
world = { path = "../../world" }
core_executor = {path = "../../core_executor"}
platform = { path = "../../platform" }
smol-potat = "1.1.2"
smol = "1.2.5"
futures-lite = "1.12.0"
futures-util = "0.3.23"
log = "0.4.17"
