[package]
name = "nshell"
version = "0.1.0"
edition = "2021"

[dependencies]
core_executor = { path = "../../core_executor" }
input = { path = "../../input" }
platform = { path = "../../platform" }
plugin_loader = { path = "../../plugin_loader" }
render = { path = "../../render" }
world = { path = "../../world" }
logger = { path = "../../logger" }

smol = "1.2.5"
futures-util = "0.3.23"
serde = { version = "1.0.130", features = ["derive"] }
structopt-yaml = "0.4.6"

# workspace
async-lock = { workspace = true }
futures-lite = { workspace = true }
structopt = { workspace = true }
