[package]
name = "core_executor"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.33"
async-executor = "1.4.1"
async-channel = "1.7.1"
async-oneshot = "0.5.0"
core_affinity = "0.7.2"
futures-lite = "1.12"

[dev-dependencies]
futures-util = "0.3.23"
