[package]
name = "core_executor"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-lite = "1.12"
futures-channel = "0.3.21"
async-executor = "1.4.1"
core_affinity = "0.5.10"

[dev-dependencies]
