[workspace]
members = [
    "crates/state",
    "crates/core_executor",
    "crates/plugin_loader",
    "crates/nshell",

    # these plugin crates should not be depended upon by anything else
    "crates/plugins/gilrs_input_plugin",
    "crates/plugins/sdl2_input_plugin",
]
