[package]
name = "render"
version = "0.1.0"
edition = "2021"

[dependencies]
core_executor = { path = "../core_executor" }
platform = { path = "../platform" }
world = { path = "../world" }
models = { path = "../models" }

ash = "0.37.2+1.3.238"
ash-window = "0.11.0"
async-lock = "2.5.0"
image = "0.24.3"
nalgebra = "0.31.1"
thiserror = "1.0.34"
