[package]
name = "render"
version = "0.1.0"
edition = "2021"

[dependencies]
platform = { path = "../platform" }
world = { path = "../world" }
models = { path = "../models" }

# workspace
ash = { workspace = true }
ash-window = { workspace = true }
async-lock = { workspace = true }
image = { workspace = true }
nalgebra = { workspace = true }
thiserror = { workspace = true }
