[package]
name = "platform"
version = "0.1.0"
edition = "2021"

[dependencies]
input = { path = "../input" }

# workspace
sdl2 = { workspace = true }
raw-window-handle = { workspace = true }
thiserror= { workspace = true }
