[package]
name = "platform"
version = "0.1.0"
edition = "2021"

[dependencies]
sdl2 = { version = "0.35.2", features = ["raw-window-handle"] }
raw-window-handle = "0.4.2"
core_executor = { path = "../core_executor" }
input = { path = "../input" }
thiserror = "1.0.32"
