[package]
name = "nshell"
version = "0.1.0"
edition = "2021"

[dependencies]
plugin_loader = { path = "../plugin_loader" }
state = { path = "../state" }
core_executor = {path = "../core_executor"}
futures-lite = "1.12.0"
smol-potat = "1.1.2"
