[package]
name = "nshell"
version = "0.1.0"
edition = "2021"

[dependencies]
plugin_loader = { path = "../plugin_loader" }
state = { path = "../state" }
core_executor = {path = "../core_executor"}
smol-potat = "1.1.2"
smol = "1.2.5"
futures = "0.3"
