[package]
name = "world"
version = "0.1.0"
edition = "2021"

[dependencies]
models = { path = "../models" }
network = { path = "../network" }
input = { path = "../input" }

# workspace deps
async-lock = { workspace = true }
parry3d = { workspace = true }
nalgebra = { workspace = true }
thiserror= { workspace = true }
serde = { workspace = true }
