[package]
name = "world"
version = "0.1.0"
edition = "2021"

[dependencies]
models = { path = "../models" }
network = { path = "../network" }
input = { path = "../input" }
logger = { path = "../logger" }
plugin_self = { path = "../plugin_self" }

# workspace deps
async-lock = { workspace = true }
glam = { workspace = true }
thiserror= { workspace = true }
serde = { workspace = true }
