[package]
name = "world"
version = "0.1.0"
edition = "2021"

[dependencies]
core_executor = { path = "../core_executor" }
models = { path = "../models" }
network = { path = "../network" }
input = { path = "../input" }

async-lock = "2.5.0"
async-io = "1.9.0"
bytemuck = "1.12.1"
histogram = "0.6.9"
zstd = "0.11.2+zstd.1.5.2"
nalgebra = "0.31.1"
thiserror = "1.0.33"
futures-lite = "1.12.0"
parry3d = "0.9.0"