[package]
name = "plugin_loader"
publish = false
version = "0.1.0"
edition = "2021"

[dependencies]
libloading = "0.7"
log = "0.4"
tempdir = "0.3.7"
thiserror = "1"
core_executor = { path = "../core_executor" }

[target.'cfg(unix)'.dependencies]
cstr = "0.2.10"
libc = "0.2.129"
once_cell = "1.13.0"
proc-maps = "0.2.1"

futures-lite = "1.12.0"
async-io = "1.7.0"

[dev-dependencies]
cmd_lib = "1.3"
function_name = "0.3"
smol-potat = "1.1.2"

[build-dependencies]
const-gen = "1.2.0"
