[package]
name = "plugin_loader"
publish = false
version = "0.1.0"
edition = "2021"

[dependencies]
libloading = "0.7"
log = "0.4"
thiserror = "1"
tempdir = "0.3.7"

[dev-dependencies]
cmd_lib = "1.3"
function_name = "0.3"

[build-dependencies]
const-gen = "1.1"
